#!/usr/bin/env bash

# version to be used
version=5.24.0

THISDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

declare -a pkgs=(
extra-cmake-modules
attica-qt5
karchive-qt5
kcodecs-qt5
kconfig-qt5
kcoreaddons-qt5
kdbusaddons-qt5
kguiaddons-qt5
ki18n-qt5
kwindowsystem-qt5
kcrash-qt5
kglobalaccel-qt5
kidletime-qt5
kimageformats-qt5
kitemmodels-qt5
kitemviews-qt5
kdoctools-qt5
kjs-qt5
kplotting-qt5
kwidgetsaddons-qt5
solid-qt5
)

for pkg in "${pkgs[@]}"; do
  pushd ${THISDIR}/../mingw-w64-${pkg}
  if [ $(awk '/^pkgver/' PKGBUILD) != 'pkgver=5.24.0' ]; then
    sed "/pkgver=.*/c\pkgver=${version}" -i PKGBUILD
    updpkgsums
  fi
  popd
done
